### ISSUE TITLE
Compute instance dashboard taking a lot of RAM on google cloud shell causing it to crash

### ISSUE THREAD

**Issue by Rstar1998** [turbot/steampipe-mod-gcp-insights#35]
So I have been using steampipe compute instance dashboard. But while running it on cloud shell , the process taking a lot of RAM on google cloud shell causing it to crash. I have seen the memory to increase beyond 8 GB. Can query optimization solve this issue ?

**Comment by misraved** [comment]
Hello @Rstar1998 , this seems like a pretty interesting observation. I haven't tried out dashboards on google cloud shell as of now, but this looks like a good place to start with.

Before diving into it, could you please answer a few questions which would help me in debugging the issue:
- Which version of gcp plugin are you using, we recently released `v0.27.0` version of gcp plugin which includes significant memory management and caching improvements.
- Do you observe similar issues when you are running other dashboards? like KMS or compute disks?
